### ISSUE TITLE
Bug when exporting ECH, DTA and SEQ

### ISSUE THREAD

**Issue by nomont** [itesla/ipst#132]
There seems to be a bug linked to the export of an empty file.
It was expected that the file would be empty because I used ContingenciesProviderFactoryMock.

```
[itesla@pf9sositesla tmp]$ itools export-eurostag --case-basename 20161020_1730_SN4_FR0 --case-dir  ~/caserepo/CIM/SN/2016/10/20/ --case-format CIM1 --output-dir ./
loading case...
exporting ech...
exporting dta...
exporting seq...
java.lang.IllegalArgumentException: [SHRINKWRAP-93] Cannot use this JDK-based implementation to export as ZIP an archive with no content: ed069f97-cbad-4124-a882-485d54c13147.jar: 0 assets
        at org.jboss.shrinkwrap.impl.base.exporter.zip.ZipExporterDelegate.<init>(ZipExporterDelegate.java:43)
        at org.jboss.shrinkwrap.impl.base.exporter.zip.ZipExporterImpl.exportAsInputStream(ZipExporterImpl.java:48)
        at org.jboss.shrinkwrap.impl.base.exporter.AbstractStreamExporterImpl.exportTo(AbstractStreamExporterImpl.java:115)
        at org.jboss.shrinkwrap.impl.base.exporter.AbstractStreamExporterImpl.exportTo(AbstractStreamExporterImpl.java:148)
        at org.jboss.shrinkwrap.impl.base.exporter.AbstractStreamExporterImpl.exportTo(AbstractStreamExporterImpl.java:167)
        at eu.itesla_project.eurostag.EurostagExportTool.run(EurostagExportTool.java:111)
        at eu.itesla_project.commons.tools.Main.main(Main.java:95)

```

**Comment by nomont** [comment]
It might also be the case that the error is linked to the fact that the connection to the Dynamic Database failed, that the error was catched and that it show up lately here.
