### ISSUE TITLE
IllegalArgumentException in LocalOnlineApplication

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#172]
When we use the old fashion parameters of online-workflow-control tool, an IllegalArgumentException is thrown from OlineDbMVStore.java because the case file parameter is not set. This exception is not thrown if we use the --case-file parameter.
If we set the case-file parameter with a default value in the config.xml (online-default-parameter), there is another (expected) exception:
```
java.lang.RuntimeException: caseFile and ( baseCaseDate, caseType, countries ) are mutually exclusive options
```

The line from where the exception is thrown in OlineDbMVStore.java:
```
storedParametersMap.put(STORED_PARAMETERS_CASE_FILE_KEY, parameters.getCaseFile());
```

Here the full stack trace:
```
[itesla@pf9sositesla .itesla]$ itools online-workflow-control --start-workflow  --case-type FO --base-case 2016-11-08T20:30:00.000+01:00  --states 1
starting Online Workflow, basecase 2016-11-08T20:30:00.000+01:00
java.lang.RuntimeException: java.lang.IllegalArgumentException: The value may not be null [1.4.191/0]
        at eu.itesla_project.online.LocalOnlineApplication.startWorkflow(LocalOnlineApplication.java:273)
        ...
Caused by: java.lang.IllegalArgumentException: The value may not be null [1.4.191/0]
        at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:736)
        at org.h2.mvstore.DataUtils.checkArgument(DataUtils.java:723)
        at org.h2.mvstore.MVMap.put(MVMap.java:116)
        at eu.itesla_project.online.db.OnlineDbMVStore.storeWorkflowParameters(OnlineDbMVStore.java:821)
```

**Comment by CBiasuzzi** [comment]
I've committed a fix to this issue (PR #175)
